### ISSUE TITLE
Missing trailing punctuation

### ISSUE THREAD

**Issue by koral--** [bitrise-io/blog#196]
After finding this one: https://github.com/bitrise-io/blog/pull/195/files#diff-7b3e48cd54e7790911d118bce71467b1R9
I've spotted a few more when briefly reading rest of the blog:
- possible missing dot: https://github.com/bitrise-io/blog/pull/181/files#diff-49ee68d7a591ffc1fe7a5450dd142585R9
- missing closing parenthesis: https://github.com/bitrise-io/blog/pull/182/files#diff-3a16381ba912d00736ab14ee94bc712dR101

**Comment by viktorbenei** [comment]
@annabatki please check & fix ;)

**Comment by annabatki** [comment]
Oh, these have been fixed :)
https://giphy.com/gifs/just-thanks-KJ1f5iTl4Oo7u
